package com.fps.idl.Sensors;

/**
* com/fps/idl/Sensors/ReadingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public final class ReadingHolder implements org.omg.CORBA.portable.Streamable
{
  public com.fps.idl.Sensors.Reading value = null;

  public ReadingHolder ()
  {
  }

  public ReadingHolder (com.fps.idl.Sensors.Reading initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.fps.idl.Sensors.ReadingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.fps.idl.Sensors.ReadingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.fps.idl.Sensors.ReadingHelper.type ();
  }

}
