package com.fps.idl.Sensors;

/**
* com/fps/idl/Sensors/SensorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public final class SensorHolder implements org.omg.CORBA.portable.Streamable
{
  public com.fps.idl.Sensors.Sensor value = null;

  public SensorHolder ()
  {
  }

  public SensorHolder (com.fps.idl.Sensors.Sensor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.fps.idl.Sensors.SensorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.fps.idl.Sensors.SensorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.fps.idl.Sensors.SensorHelper.type ();
  }

}
