package com.fps.idl.Sensors;


/**
* com/fps/idl/Sensors/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public interface SensorOperations 
{
  String name ();
  com.fps.idl.Sensors.WarningLevel current ();
  void current (com.fps.idl.Sensors.WarningLevel newCurrent);
  com.fps.idl.Sensors.Reading currentReading ();
  void currentReading (com.fps.idl.Sensors.Reading newCurrentReading);
  String zone ();
  void zone (String newZone);
  void set_sensor_status (com.fps.idl.Sensors.Status stat);
  com.fps.idl.Sensors.Status get_sensor_status ();
  String get_pair_name ();
} // interface SensorOperations
