package com.fps.idl.Sensors;


/**
* com/fps/idl/Sensors/Status.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public class Status implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static com.fps.idl.Sensors.Status[] __array = new com.fps.idl.Sensors.Status [__size];

  public static final int _ON = 0;
  public static final com.fps.idl.Sensors.Status ON = new com.fps.idl.Sensors.Status(_ON);
  public static final int _OFF = 1;
  public static final com.fps.idl.Sensors.Status OFF = new com.fps.idl.Sensors.Status(_OFF);
  public static final int _RESET = 2;
  public static final com.fps.idl.Sensors.Status RESET = new com.fps.idl.Sensors.Status(_RESET);

  public int value ()
  {
    return __value;
  }

  public static com.fps.idl.Sensors.Status from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Status (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Status
