package com.fps.idl.Sensors;


/**
* com/fps/idl/Sensors/WarningLevel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public class WarningLevel implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static com.fps.idl.Sensors.WarningLevel[] __array = new com.fps.idl.Sensors.WarningLevel [__size];

  public static final int _UNKNOWN = 0;
  public static final com.fps.idl.Sensors.WarningLevel UNKNOWN = new com.fps.idl.Sensors.WarningLevel(_UNKNOWN);
  public static final int _MINOR = 1;
  public static final com.fps.idl.Sensors.WarningLevel MINOR = new com.fps.idl.Sensors.WarningLevel(_MINOR);
  public static final int _AVERAGE = 2;
  public static final com.fps.idl.Sensors.WarningLevel AVERAGE = new com.fps.idl.Sensors.WarningLevel(_AVERAGE);
  public static final int _HIGH = 3;
  public static final com.fps.idl.Sensors.WarningLevel HIGH = new com.fps.idl.Sensors.WarningLevel(_HIGH);

  public int value ()
  {
    return __value;
  }

  public static com.fps.idl.Sensors.WarningLevel from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected WarningLevel (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class WarningLevel
