package com.fps.idl.Sensors;


/**
* com/fps/idl/Sensors/WarningLevelHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

abstract public class WarningLevelHelper
{
  private static String  _id = "IDL:Sensors/WarningLevel:1.0";

  public static void insert (org.omg.CORBA.Any a, com.fps.idl.Sensors.WarningLevel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.fps.idl.Sensors.WarningLevel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.fps.idl.Sensors.WarningLevelHelper.id (), "WarningLevel", new String[] { "UNKNOWN", "MINOR", "AVERAGE", "HIGH"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.fps.idl.Sensors.WarningLevel read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.fps.idl.Sensors.WarningLevel.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.fps.idl.Sensors.WarningLevel value)
  {
    ostream.write_long (value.value ());
  }

}
