package com.fps.idl.RMC;


/**
* com/fps/idl/RMC/_RMCStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public class _RMCStub extends org.omg.CORBA.portable.ObjectImpl implements com.fps.idl.RMC.RMC
{

  public void raiseAlarm (com.fps.idl.RMC.AlarmData anAlarm)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("raiseAlarm", true);
                com.fps.idl.RMC.AlarmDataHelper.write ($out, anAlarm);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                raiseAlarm (anAlarm        );
            } finally {
                _releaseReply ($in);
            }
  } // raiseAlarm

  public void registerAgency (String who, String contact_details, String zone)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerAgency", true);
                $out.write_string (who);
                $out.write_string (contact_details);
                $out.write_string (zone);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerAgency (who, contact_details, zone        );
            } finally {
                _releaseReply ($in);
            }
  } // registerAgency

  public void registerUser (String who, String contact_details, String zone)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerUser", true);
                $out.write_string (who);
                $out.write_string (contact_details);
                $out.write_string (zone);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerUser (who, contact_details, zone        );
            } finally {
                _releaseReply ($in);
            }
  } // registerUser

  public com.fps.idl.Sensors.WarningLevel currentAlarms ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("currentAlarms", true);
                $in = _invoke ($out);
                com.fps.idl.Sensors.WarningLevel $result = com.fps.idl.Sensors.WarningLevelHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return currentAlarms (        );
            } finally {
                _releaseReply ($in);
            }
  } // currentAlarms

  public String interogate_Sensor (String who, String zone, String sensor)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("interogate_Sensor", true);
                $out.write_string (who);
                $out.write_string (zone);
                $out.write_string (sensor);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return interogate_Sensor (who, zone, sensor        );
            } finally {
                _releaseReply ($in);
            }
  } // interogate_Sensor

  public void add_LMS (String name)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("add_LMS", true);
                $out.write_string (name);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                add_LMS (name        );
            } finally {
                _releaseReply ($in);
            }
  } // add_LMS

  public String getLmsLogs ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLmsLogs", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLmsLogs (        );
            } finally {
                _releaseReply ($in);
            }
  } // getLmsLogs

  public boolean confirmAlarm (com.fps.idl.RMC.AlarmData alarmData)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("confirmAlarm", true);
                com.fps.idl.RMC.AlarmDataHelper.write ($out, alarmData);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return confirmAlarm (alarmData        );
            } finally {
                _releaseReply ($in);
            }
  } // confirmAlarm

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RMC/RMC:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RMCStub
