package com.fps.idl.RMC;


/**
* com/fps/idl/RMC/AlarmData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public final class AlarmData implements org.omg.CORBA.portable.IDLEntity
{
  public com.fps.idl.LMS.Alarm aReading = null;
  public String aConfirmingSensor = null;

  public AlarmData ()
  {
  } // ctor

  public AlarmData (com.fps.idl.LMS.Alarm _aReading, String _aConfirmingSensor)
  {
    aReading = _aReading;
    aConfirmingSensor = _aConfirmingSensor;
  } // ctor

} // class AlarmData
