package com.fps.idl.RMC;

/**
* com/fps/idl/RMC/RMCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public final class RMCHolder implements org.omg.CORBA.portable.Streamable
{
  public com.fps.idl.RMC.RMC value = null;

  public RMCHolder ()
  {
  }

  public RMCHolder (com.fps.idl.RMC.RMC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.fps.idl.RMC.RMCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.fps.idl.RMC.RMCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.fps.idl.RMC.RMCHelper.type ();
  }

}
