package com.fps.idl.RMC;


/**
* com/fps/idl/RMC/RMCHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

abstract public class RMCHelper
{
  private static String  _id = "IDL:RMC/RMC:1.0";

  public static void insert (org.omg.CORBA.Any a, com.fps.idl.RMC.RMC that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.fps.idl.RMC.RMC extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.fps.idl.RMC.RMCHelper.id (), "RMC");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.fps.idl.RMC.RMC read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RMCStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.fps.idl.RMC.RMC value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.fps.idl.RMC.RMC narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.fps.idl.RMC.RMC)
      return (com.fps.idl.RMC.RMC)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.fps.idl.RMC._RMCStub stub = new com.fps.idl.RMC._RMCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.fps.idl.RMC.RMC unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.fps.idl.RMC.RMC)
      return (com.fps.idl.RMC.RMC)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.fps.idl.RMC._RMCStub stub = new com.fps.idl.RMC._RMCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
