package com.fps.idl.RMC;


/**
* com/fps/idl/RMC/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public interface RMCOperations 
{
  void raiseAlarm (com.fps.idl.RMC.AlarmData anAlarm);
  void registerAgency (String who, String contact_details, String zone);
  void registerUser (String who, String contact_details, String zone);
  com.fps.idl.Sensors.WarningLevel currentAlarms ();
  String interogate_Sensor (String who, String zone, String sensor);
  void add_LMS (String name);
  String getLmsLogs ();
  boolean confirmAlarm (com.fps.idl.RMC.AlarmData alarmData);
} // interface RMCOperations
