package com.fps.idl.RMC;


/**
* com/fps/idl/RMC/RMCPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public abstract class RMCPOA extends org.omg.PortableServer.Servant
 implements com.fps.idl.RMC.RMCOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("raiseAlarm", new java.lang.Integer (0));
    _methods.put ("registerAgency", new java.lang.Integer (1));
    _methods.put ("registerUser", new java.lang.Integer (2));
    _methods.put ("currentAlarms", new java.lang.Integer (3));
    _methods.put ("interogate_Sensor", new java.lang.Integer (4));
    _methods.put ("add_LMS", new java.lang.Integer (5));
    _methods.put ("getLmsLogs", new java.lang.Integer (6));
    _methods.put ("confirmAlarm", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RMC/RMC/raiseAlarm
       {
         com.fps.idl.RMC.AlarmData anAlarm = com.fps.idl.RMC.AlarmDataHelper.read (in);
         this.raiseAlarm (anAlarm);
         out = $rh.createReply();
         break;
       }

       case 1:  // RMC/RMC/registerAgency
       {
         String who = in.read_string ();
         String contact_details = in.read_string ();
         String zone = in.read_string ();
         this.registerAgency (who, contact_details, zone);
         out = $rh.createReply();
         break;
       }

       case 2:  // RMC/RMC/registerUser
       {
         String who = in.read_string ();
         String contact_details = in.read_string ();
         String zone = in.read_string ();
         this.registerUser (who, contact_details, zone);
         out = $rh.createReply();
         break;
       }

       case 3:  // RMC/RMC/currentAlarms
       {
         com.fps.idl.Sensors.WarningLevel $result = null;
         $result = this.currentAlarms ();
         out = $rh.createReply();
         com.fps.idl.Sensors.WarningLevelHelper.write (out, $result);
         break;
       }

       case 4:  // RMC/RMC/interogate_Sensor
       {
         String who = in.read_string ();
         String zone = in.read_string ();
         String sensor = in.read_string ();
         String $result = null;
         $result = this.interogate_Sensor (who, zone, sensor);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // RMC/RMC/add_LMS
       {
         String name = in.read_string ();
         this.add_LMS (name);
         out = $rh.createReply();
         break;
       }

       case 6:  // RMC/RMC/getLmsLogs
       {
         String $result = null;
         $result = this.getLmsLogs ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // RMC/RMC/confirmAlarm
       {
         com.fps.idl.RMC.AlarmData alarmData = com.fps.idl.RMC.AlarmDataHelper.read (in);
         boolean $result = false;
         $result = this.confirmAlarm (alarmData);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RMC/RMC:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RMC _this() 
  {
    return RMCHelper.narrow(
    super._this_object());
  }

  public RMC _this(org.omg.CORBA.ORB orb) 
  {
    return RMCHelper.narrow(
    super._this_object(orb));
  }


} // class RMCPOA
