package com.fps.idl.Users;


/**
* com/fps/idl/Users/UserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public interface UserOperations 
{
  void receive_email (com.fps.idl.RMC.AlarmData alarm);
} // interface UserOperations
