package com.fps.idl.Users;


/**
* com/fps/idl/Users/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public interface User extends UserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface User
