package com.fps.idl.Users;

/**
* com/fps/idl/Users/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public com.fps.idl.Users.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (com.fps.idl.Users.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.fps.idl.Users.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.fps.idl.Users.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.fps.idl.Users.UserHelper.type ();
  }

}
