package com.fps.idl.LMS;


/**
* com/fps/idl/LMS/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

public interface LMSOperations 
{
  String name ();
  com.fps.idl.LMS.Alarm[] log ();

  //assuming a sensor can belong to multiple zones
  void add_Sensor (com.fps.idl.Sensors.Sensor aSensor, String zone);
  com.fps.idl.LMS.Alarm get_currrent_alarm_status (String zone);
  String[] get_Sensors ();
  void raise_Alarm (com.fps.idl.LMS.Alarm aReading);
} // interface LMSOperations
