package com.fps.idl.LMS;


/**
* com/fps/idl/LMS/LogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Saturday, 14 March 2015 9:23:59 AM EST
*/

abstract public class LogHelper
{
  private static String  _id = "IDL:LMS/Log:1.0";

  public static void insert (org.omg.CORBA.Any a, com.fps.idl.LMS.Alarm[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.fps.idl.LMS.Alarm[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = com.fps.idl.LMS.AlarmHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (com.fps.idl.LMS.LogHelper.id (), "Log", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.fps.idl.LMS.Alarm[] read (org.omg.CORBA.portable.InputStream istream)
  {
    com.fps.idl.LMS.Alarm value[] = null;
    int _len0 = istream.read_long ();
    value = new com.fps.idl.LMS.Alarm[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = com.fps.idl.LMS.AlarmHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.fps.idl.LMS.Alarm[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      com.fps.idl.LMS.AlarmHelper.write (ostream, value[_i0]);
  }

}
