package com.fps.idl.LMS;


/**
* com/fps/idl/LMS/ZoneCoverageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/fps/idl/FPS.idl
* Friday, 13 March 2015 11:15:37 PM EST
*/

public final class ZoneCoverageHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ZoneCoverageHolder ()
  {
  }

  public ZoneCoverageHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.fps.idl.LMS.ZoneCoverageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.fps.idl.LMS.ZoneCoverageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.fps.idl.LMS.ZoneCoverageHelper.type ();
  }

}
